### ISSUE TITLE
Deliverable D- Spreadsheet with API Test Inputs

### ISSUE THREAD

**Issue by mtrimp2** [mtrimp2/smarter-university-system#18]
Activity of #7 

A crucial part of the quality assurance procedures is the testing of the system boundaries. More specifically, the Application Programming Interface (API) through which the user interface and other systems interact with the backend must be robust even when it receives requests that violate the API specification. Your task is to create test inputs for an API endpoint.
The endpoint exposes a new capability of the SUS that has come out of feedback from sprint reviews in which stakeholders expressed the desire to be able to show an activity stream in the sidebar of the SUS user interface. Lecturers and students alike can post to that activity stream as a means to provide status updates or to prompt others to complete tasks.
The primary component of an activity post is the message text, which is specified in the POST body. However, several additional parameters are specified in the URL to that endpoint as shown in this example:
POST /activity?flag=IMPORTANT&directed=TRUE&recipients=cdarwin body: I’d like to discuss the project
The list of all input parameters is shown in the table below. Your task is to create test cases that are effective in uncovering defects using the category partition and boundary analysis methods discussed in class. The goal of your test cases is to mimic both nominal use and invalid use of the API endpoint. That is, you should specify test cases where the values of parameters adhere to the specified constraints. You should also specify test cases that slightly deviate from the format but may be reasonably considered valid from a common sense perspective. Finally, you should provide values that are clearly outside the specified format. After all, your goal is to expose any coding mistakes and make sure that when real users call the endpoints, they are not able to break the system.

Remember, a test case means you call the API endpoint and you specify values for each of the parameters that are listed above. Example:
POST /activity?flag=IMPORTANT&directed=TRUE&recipients=cdarwin body: I’d like to discuss the project
Hence, for a single test case, you must choose what value to provide for each of the input parameters. Of course, some parameters may not have a value at all for some test cases. In the example URL above, only some of the parameters have been specified. In that situation, you leave the value for that parameter empty.

**DELIVERABLE:**
A spreadsheet where each row represents a test case and each column the value of the respective parameter. The submitted spreadsheet should be named activities_team_<number>.xlsx
Where <number> is the number of our team.

**Comment by mtrimp2** [comment]
Might split this into two or three issues at some point- maybe brainstorm test inputs, put them in the spreadsheet, submit it

**Comment by hvrgupta** [comment]
Team_2 API Test Input speadsheet:
https://docs.google.com/spreadsheets/d/19OPRWpy0yuu_7Z9cATya88UsaP3Jrxe-VzK3Z5xzhc0/edit#gid=0
