### ISSUE TITLE
Prepare deliverables B-D for submission

### ISSUE THREAD

**Issue by mtrimp2** [mtrimp2/smarter-university-system#29]
After completion of #13 , #14 , #18 

Deliverables B-D will be put into proper format to be submitted by the project due date.

Deliverable B: Submit your diagram in Graphviz format. The trees should be
submitted in one document named Team_2_Bigraph.txt. Label the graph with the name of the team member. For instance, for John Doe, the first line of the graph should be “digraph john_doe {“
https://docs.google.com/document/d/1RHvArYGHSB3KwlUQbNsUEDtWbkK0xNjfV_OTVVjUG1Q/edit?usp=sharing 

Deliverable C: Take the spreadsheet with the user stories from Task 3 and add columns to
capture the requirements rank for each of the team members as well as the total overall
requirements rank. Submit the document in xlsx (Excel) format. The file must be named
Team_2_UserStories.xlsx Each requirement is represented as a row in the spreadsheet. The first column contains the requirements ID, the second column contains the name of the epic, and the third column
contains the user story. A template for this spreadsheet is provided in the files for the
assignment
https://docs.google.com/spreadsheets/d/192WKt8x9YCXJdqIw67TziABgtJfHNlH7j5Y0qhmYpos/edit#gid=0 

Deliverable D: API Test inputs. A spreadsheet where each row represents a test case and each column the
value of the respective parameter. The submitted spreadsheet should be named
activities_team_2.xlsx

**Comment by joshuag1214** [comment]
Pushed deliverables for submission
